export default {
  OPEN_CREATE_NOTE_MODAL: " OPEN_CREATE_NOTE_MODAL",
  GET_FOOD_DATA_SUCCESS: "GET_FOOD_DATA_SUCCESS",
  GET_FOOD_DATA_FAILURE: "GET_FOOD_DATA_FAILURE",
  GET_FOOD_DATA_REQUEST: "GET_FOOD_DATA_REQUEST",
};
